package claude

import (
	"context"
	"errors"
	"io"
	"log"
	"net"
	"net/http"
	"net/http/httputil"
	"net/url"
	"time"
)

// DefaultAccountConcurrency is the default number of inference requests one account
// serves at once, and the size of its connection pool; requests beyond it are refused
// instead of queued.
const DefaultAccountConcurrency = 32

// errUpgradeUnsupported is returned from ModifyResponse when the upstream switches
// protocols, which turns the response into a 502.
var errUpgradeUnsupported = errors.New("protocol upgrade unsupported")

// newTransport returns the outbound connection pool of concurrency connections. It ignores proxy environment
// variables, so authenticated mode's configureProxy is the only proxy source, and it
// disables compression so bodies and Accept-Encoding pass through unchanged.
func newTransport(concurrency int) *http.Transport {
	return &http.Transport{
		Proxy:                 nil,
		DialContext:           (&net.Dialer{Timeout: 10 * time.Second, KeepAlive: 30 * time.Second}).DialContext,
		ForceAttemptHTTP2:     true,
		MaxIdleConns:          concurrency,
		MaxIdleConnsPerHost:   concurrency,
		MaxConnsPerHost:       concurrency,
		IdleConnTimeout:       30 * time.Second,
		TLSHandshakeTimeout:   10 * time.Second,
		ResponseHeaderTimeout: 30 * time.Second,
		ExpectContinueTimeout: time.Second,
		DisableCompression:    true,
	}
}

// declaredLength ends a request body at its declared length. After that many bytes
// the transport reads once more to confirm EOF, and net/http may have closed the
// request body by then, when the response header was written; reading it would fail
// and the transport would close the upstream connection in the middle of the response.
type declaredLength struct {
	io.ReadCloser
	remaining int64
}

// Read reads at most the bytes still declared, then returns io.EOF without reading
// the wrapped body.
func (b *declaredLength) Read(p []byte) (int, error) {
	if b.remaining <= 0 {
		return 0, io.EOF
	}
	n, err := b.ReadCloser.Read(p[:min(int64(len(p)), b.remaining)])
	b.remaining -= int64(n)
	return n, err
}

// newReverseProxy configures the standard library reverse proxy that does the actual
// forwarding to target through transport, which dispatches by the request's account.
// inspect sees every upstream response, including one that is then rejected.
func newReverseProxy(target *url.URL, transport http.RoundTripper, inspect func(*http.Response) error) *httputil.ReverseProxy {
	return &httputil.ReverseProxy{
		Rewrite: func(p *httputil.ProxyRequest) {
			p.SetURL(target)
			// Rewrite receives a cleaned query; retain the original query encoding.
			p.Out.URL.RawQuery = p.In.URL.RawQuery
			accountFrom(p.In.Context()).replaceClientAuthentication(p.Out.Header)
			// Transport may retry idempotent requests only when their body is replayable.
			// Every forwarded request gets a non-replayable body, including empty ones.
			if p.Out.Body == nil || p.Out.Body == http.NoBody {
				p.Out.Body = io.NopCloser(http.NoBody)
			} else if p.Out.ContentLength > 0 {
				p.Out.Body = &declaredLength{p.Out.Body, p.Out.ContentLength}
			}
			p.Out.GetBody = nil
		},
		Transport: transport,
		// Flush after every write so each streamed event reaches the client at once.
		FlushInterval: -1,
		// Its messages can include URLs and headers.
		ErrorLog:     log.New(io.Discard, "", 0),
		ErrorHandler: respondUpstreamUnavailable,
		ModifyResponse: func(res *http.Response) error {
			if err := inspect(res); err != nil {
				return err
			}
			return rejectUpgrade(res)
		},
	}
}

// respondUpstreamUnavailable answers 502 when the upstream cannot be reached, times
// out, or is rejected by rejectUpgrade. It marks the request state so the records
// treat the response as generated by the gateway.
func respondUpstreamUnavailable(w http.ResponseWriter, r *http.Request, _ error) {
	if state, ok := r.Context().Value(stateKey{}).(*requestState); ok {
		state.upstreamUnavailable = true
	}
	http.Error(w, "upstream unavailable", http.StatusBadGateway)
}

// rejectUpgrade refuses protocol upgrades such as WebSocket. An upgraded connection is
// a raw byte stream that would bypass the deadlines and capture.
func rejectUpgrade(r *http.Response) error {
	if r.StatusCode == http.StatusSwitchingProtocols {
		return errUpgradeUnsupported
	}
	return nil
}

// serveWithLimits forwards r until it ends, has moved no byte either way (up is the
// request body, down the response) for limits.Idle, or has run for limits.MaxRequest;
// state.cut then says which limit ended it. The server's own read and write timeouts
// are moved to the total limit, or they would end a longer request. A cut cancels the
// upstream side and moves both deadlines to now, because a client that stops reading
// would otherwise keep the response write blocked, and one that stops sending its body
// the body read.
func serveWithLimits(proxy http.Handler, limits Limits, state *requestState, up *countingReader, down *countingWriter, r *http.Request) {
	ctx, cancel := context.WithCancel(r.Context())
	defer cancel()
	controller := http.NewResponseController(down)
	end := time.Now().Add(limits.MaxRequest)
	if controller.SetReadDeadline(end) != nil || controller.SetWriteDeadline(end) != nil {
		http.Error(down, "deadlines unavailable", http.StatusInternalServerError)
		return
	}
	dog := startWatchdog(limits.Idle, limits.MaxRequest, func() {
		cancel()
		_ = controller.SetReadDeadline(time.Now())
		_ = controller.SetWriteDeadline(time.Now())
	})
	up.dog, down.dog = dog, dog
	// The connection may serve another keep-alive request after this one. Deferred
	// calls run when ReverseProxy aborts the handler with a panic, too.
	defer func() {
		state.cut = dog.stop()
		if controller.SetReadDeadline(time.Time{}) != nil || controller.SetWriteDeadline(time.Time{}) != nil {
			log.Print("gateway deadline reset failed")
		}
	}()
	proxy.ServeHTTP(down, r.WithContext(ctx))
}
